const TASTE_DIVE_API_KEY = '1049527-DanailDa-36868088';
const TASTE_DIVE_BASE_URL = '/api/similar';
const OPEN_LIBRARY_BASE_URL = 'https://openlibrary.org';
const LIBRE_TRANSLATE_BASE_URL = 'https://translate.argosopentech.com'; // More reliable instance

const titleMap = {
    // International Classics
    'Чужденецът': 'The Stranger',
    'Метаморфозата': 'The Metamorphosis',
    'Процесът': 'The Trial',
    'Замъкът': 'The Castle',
    '1984': '1984',
    'Прекрасният нов свят': 'Brave New World',
    'Гордост и предразсъдъци': 'Pride and Prejudice',
    'Джейн Еър': 'Jane Eyre',
    'Гроздовете на гнева': 'The Grapes of Wrath',
    'Великият Гетсби': 'The Great Gatsby',
    'Моби Дик': 'Moby-Dick',
    'Война и мир': 'War and Peace',
    'Престъпление и наказание': 'Crime and Punishment',
    'Братя Карамазови': 'The Brothers Karamazov',
    'Мадам Бовари': 'Madame Bovary',
    'Дон Кихот': 'Don Quixote',
    'Одисей': 'The Odyssey',
    'Илиада': 'The Iliad',
    'Анна Каренина': 'Anna Karenina',
    'На западния фронт нищо ново': 'All Quiet on the Western Front',
    'Кандид': 'Candide',
    'Орловото гнездо': 'Wuthering Heights',
    'Хамлет': 'Hamlet',
    'Ромео и Жулиета': 'Romeo and Juliet',
    'Макбет': 'Macbeth',
    'Отело': 'Othello',
    'Крал Лир': 'King Lear',
    'Сън в лятна нощ': 'A Midsummer Night\'s Dream',
    'Дванадесета нощ': 'Twelfth Night',
    'Укротяване на опърничавата': 'The Taming of the Shrew',
    'Много шум за нищо': 'Much Ado About Nothing',
    'Венецианският търговец': 'The Merchant of Venice',
    'Юлий Цезар': 'Julius Caesar',
    'Антоний и Клеопатра': 'Antony and Cleopatra',
    'Зимна приказка': 'The Winter\'s Tale',
    'Бурята': 'The Tempest',
    'Божествена комедия': 'The Divine Comedy',
    'Ад': 'Inferno',
    'Чистилище': 'Purgatorio',
    'Рай': 'Paradiso',
    'Декамерон': 'The Decameron',
    'Кентърбърийски разкази': 'The Canterbury Tales',
    'Беоулф': 'Beowulf',
    'Изгубеният рай': 'Paradise Lost',
    'Том Джоунс': 'Tom Jones',
    'Клариса': 'Clarissa',
    'Робинзон Крузо': 'Robinson Crusoe',
    'Моул Фландърс': 'Moll Flanders',
    'Емма': 'Emma',
    'Разум и чувства': 'Sense and Sensibility',
    'Доводите на разума': 'Persuasion',
    'Парк Мансфийлд': 'Mansfield Park',
    'Абатството Нортангър': 'Northanger Abbey',
    'Оливър Туист': 'Oliver Twist',
    'Дейвид Копърфийлд': 'David Copperfield',
    'Големите надежди': 'Great Expectations',
    'Мрачният дом': 'Bleak House',
    'Повест за два града': 'A Tale of Two Cities',
    'Тежки времена': 'Hard Times',
    'Малката Дорит': 'Little Dorrit',
    'Никълъс Никълби': 'Nicholas Nickleby',
    'Клубът Пикуик': 'The Pickwick Papers',
    'Мартин Чъзълуит': 'Martin Chuzzlewit',
    'Нашият общ приятел': 'Our Mutual Friend',
    'Джейн Еър': 'Jane Eyre',
    'Шърли': 'Shirley',
    'Вийет': 'Villette',
    'Професорът': 'The Professor',
  
    // Modern Classics
    'Да убиеш присмехулник': 'To Kill a Mockingbird',
    'Повелителят на мухите': 'Lord of the Flies',
    'Лолита': 'Lolita',
    'По пътя': 'On the Road',
    'Старецът и морето': 'The Old Man and the Sea',
    'Над пропастта на ръжта': 'The Catcher in the Rye',
    'Цветът пурпурен': 'The Color Purple',
    'Къщата на духовете': 'The House of the Spirits',
    'Очите им гледаха Бога': 'Their Eyes Were Watching God',
    'Не ме пускай никога': 'Never Let Me Go',
    'Чувството за край': 'The Sense of an Ending',
    'Сърцето е самотен ловец': 'The Heart Is a Lonely Hunter',
    'Убий скръндзата': 'A Confederacy of Dunces',
    'Всичко се разпада': 'Things Fall Apart',
    'Среднощни деца': 'Midnight\'s Children',
    'Светлина през август': 'Light in August',
    'Врява и безумство': 'The Sound and the Fury',
    'Докато лежах и умирах': 'As I Lay Dying',
    'Авесаломе, Авесаломе!': 'Absalom, Absalom!',
    'Портокал с часовников механизъм': 'A Clockwork Orange',
    'Слепота': 'Blindness',
    'Невидимият човек': 'Invisible Man',
    'Американски психар': 'American Psycho',
    'Любовникът на лейди Чатърли': 'Lady Chatterley\'s Lover',
    'Синовете и любовници': 'Sons and Lovers',
    'Дъгата': 'The Rainbow',
    'Жени, които обичат твърде много': 'Women in Love',
    'Женски любовници': 'Women in Love',
    'Бяла шапка': 'White Noise',
    'Белият хотел': 'The White Hotel',
    'За мишките и хората': 'Of Mice and Men',
    'Тютюнев път': 'Tobacco Road',
    'Американска трагедия': 'An American Tragedy',
    'Сестра Кери': 'Sister Carrie',
    'Уловка-22': 'Catch-22',
    'Потъването на "Титаник"': 'Titanic Down',
    'Портокал с часовников механизъм': 'A Clockwork Orange',
    'Ангелът на историята': 'The Angel of History',
    'Белият шум': 'White Noise',
    'Смъртта на Вергилий': 'The Death of Virgil',
    'Петербург': 'Petersburg',
    'Омагьосаната планина': 'The Magic Mountain',
    'Будънброкови': 'Buddenbrooks',
    'Доктор Фаустус': 'Doctor Faustus',
    'Йосиф и неговите братя': 'Joseph and His Brothers',
    'Вълшебната планина': 'The Magic Mountain',
    'Смърт във Венеция': 'Death in Venice',
    'Тъмните алеи': 'Dark Avenues',
    'Възкресение': 'Resurrection',
    'Идиот': 'The Idiot',
    'Унижените и оскърбените': 'The Insulted and Injured',
    'Бесове': 'Demons',
    'Юноша': 'The Adolescent',
    'Записки от подземието': 'Notes from Underground',
    'Бели нощи': 'White Nights',
    'Двойник': 'The Double',
    'Играчът': 'The Gambler',
    'Чичо Ваньо': 'Uncle Vanya',
    'Три сестри': 'Three Sisters',
    'Вишнева градина': 'The Cherry Orchard',
    'Чайка': 'The Seagull',
    'Иванов': 'Ivanov',
    'Степ': 'The Steppe',
    'Дуел': 'The Duel',
    'Палата № 6': 'Ward No. 6',
    'Дамата с кученцето': 'The Lady with the Dog',
    
    // Popular Modern Novels
    'Хари Потър и Философският камък': 'Harry Potter and the Sorcerer\'s Stone',
    'Хари Потър и Стаята на тайните': 'Harry Potter and the Chamber of Secrets',
    'Хари Потър и Затворникът от Азкабан': 'Harry Potter and the Prisoner of Azkaban',
    'Хари Потър и Огненият бокал': 'Harry Potter and the Goblet of Fire',
    'Хари Потър и Орденът на феникса': 'Harry Potter and the Order of the Phoenix',
    'Хари Потър и Нечистокръвния принц': 'Harry Potter and the Half-Blood Prince',
    'Хари Потър и Даровете на Смъртта': 'Harry Potter and the Deathly Hallows',
    'Фантастични животни и къде да ги намерим': 'Fantastic Beasts and Where to Find Them',
    'Куидичът през вековете': 'Quidditch Through the Ages',
    'Приказките на барда Бийдъл': 'The Tales of Beedle the Bard',
    'Играта на тронове': 'A Game of Thrones',
    'Сблъсък на крале': 'A Clash of Kings',
    'Вихър от мечове': 'A Storm of Swords',
    'Пир за врани': 'A Feast for Crows',
    'Танц с дракони': 'A Dance with Dragons',
    'Кодът на Да Винчи': 'The Da Vinci Code',
    'Ангели и демони': 'Angels & Demons',
    'Изгубеният символ': 'The Lost Symbol',
    'Инферно': 'Inferno',
    'Произход': 'Origin',
    'Цифрова крепост': 'Digital Fortress',
    'Измама': 'Deception Point',
    'Гладни игри': 'The Hunger Games',
    'В пламъци': 'Catching Fire',
    'Сойка-присмехулка': 'Mockingjay',
    'Балада за пойни птици и змии': 'The Ballad of Songbirds and Snakes',
    'Дивергенти': 'Divergent',
    'Бунтовници': 'Insurgent',
    'Предани': 'Allegiant',
    'Четири': 'Four',
    'Момичето с драконовата татуировка': 'The Girl with the Dragon Tattoo',
    'Момичето, което си играеше с огъня': 'The Girl Who Played with Fire',
    'Момичето, което разбуни гнездото на стършелите': 'The Girl Who Kicked the Hornets\' Nest',
    'Мъжът, който търсеше сянката си': 'The Girl in the Spider\'s Web',
    'Момичето, което трябваше да умре': 'The Girl Who Takes an Eye for an Eye',
    'Изчезнала': 'Gone Girl',
    'Тъмни места': 'Dark Places',
    'Остри предмети': 'Sharp Objects',
    'Момичето в влака': 'The Girl on the Train',
    'Петдесет нюанса сиво': 'Fifty Shades of Grey',
    'Петдесет нюанса по-тъмно': 'Fifty Shades Darker',
    'Петдесет нюанса освободени': 'Fifty Shades Freed',
    'Грей': 'Grey',
    'По-тъмно': 'Darker',
    'Освободени': 'Freed',
    'Здрач': 'Twilight',
    'Новолуние': 'New Moon',
    'Затъмнение': 'Eclipse',
    'Разсъмване': 'Breaking Dawn',
    'Нощен ловец': 'Midnight Sun',
    'Кратък живот': 'The Short Second Life of Bree Tanner',
    'Домакинята': 'The Host',
    'Химикът': 'The Chemist',
    
    // Science Fiction and Fantasy
    'Дюн': 'Dune',
    'Месията на Дюн': 'Dune Messiah',
    'Децата на Дюн': 'Children of Dune',
    'Бог-Император на Дюн': 'God Emperor of Dune',
    'Еретиците на Дюн': 'Heretics of Dune',
    'Домът на ордена на Дюн': 'Chapterhouse: Dune',
    'Хънтърс на Дюн': 'Hunters of Dune',
    'Пясъчни червеи на Дюн': 'Sandworms of Dune',
    'Фондацията': 'Foundation',
    'Фондацията и Империята': 'Foundation and Empire',
    'Втора Фондация': 'Second Foundation',
    'Ръбът на Фондацията': 'Foundation\'s Edge',
    'Фондацията и Земята': 'Foundation and Earth',
    'Прелюдия към Фондацията': 'Prelude to Foundation',
    'Към Фондацията': 'Forward the Foundation',
    'Аз, роботът': 'I, Robot',
    'Стоманените пещери': 'The Caves of Steel',
    'Голото слънце': 'The Naked Sun',
    'Роботите на зората': 'The Robots of Dawn',
    'Роботите и Империята': 'Robots and Empire',
    'Хобитът': 'The Hobbit',
    'Властелинът на пръстените: Задругата на пръстена': 'The Lord of the Rings: The Fellowship of the Ring',
    'Властелинът на пръстените: Двете кули': 'The Lord of the Rings: The Two Towers',
    'Властелинът на пръстените: Завръщането на краля': 'The Lord of the Rings: The Return of the King',
    'Силмарилион': 'The Silmarillion',
    'Недовършени предания': 'Unfinished Tales',
    'Децата на Хурин': 'The Children of Húrin',
    'Берен и Лутиен': 'Beren and Lúthien',
    'Падането на Гондолин': 'The Fall of Gondolin',
    'Автостопаджийският пътеводител на галактиката': 'The Hitchhiker\'s Guide to the Galaxy',
    'Ресторант на края на Вселената': 'The Restaurant at the End of the Universe',
    'Животът, Вселената и всичко останало': 'Life, the Universe and Everything',
    'Сбогом и благодаря за рибата': 'So Long, and Thanks for All the Fish',
    'Предимно безобидни': 'Mostly Harmless',
    'Още нещо': 'And Another Thing...',
    'Играта на Ендър': 'Ender\'s Game',
    'Говорителят на мъртвите': 'Speaker for the Dead',
    'Ксеноцид': 'Xenocide',
    'Децата на разума': 'Children of the Mind',
    'Сянката на Ендър': 'Ender\'s Shadow',
    'Сянката на хегемона': 'Shadow of the Hegemon',
    'Сянката на марионетката': 'Shadow Puppets',
    'Сянката на великана': 'Shadow of the Giant',
    'Сянки в полет': 'Shadows in Flight',
    '451 по Фаренхайт': 'Fahrenheit 451',
    'Марсиански хроники': 'The Martian Chronicles',
    'Нещо зло се задава насам': 'Something Wicked This Way Comes',
    'Вино от глухарчета': 'Dandelion Wine',
    'Илюстрираният човек': 'The Illustrated Man',
    'Хрониките на Нарния: Лъвът, Вещицата и Дрешникът': 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
    'Хрониките на Нарния: Принц Каспиан': 'The Chronicles of Narnia: Prince Caspian',
    'Хрониките на Нарния: Плаването на "Разсъмване"': 'The Chronicles of Narnia: The Voyage of the Dawn Treader',
    'Хрониките на Нарния: Сребърният стол': 'The Chronicles of Narnia: The Silver Chair',
    'Хрониките на Нарния: Конят и неговото момче': 'The Chronicles of Narnia: The Horse and His Boy',
    'Хрониките на Нарния: Магьосникът и неговият племенник': 'The Chronicles of Narnia: The Magician\'s Nephew',
    'Хрониките на Нарния: Последната битка': 'The Chronicles of Narnia: The Last Battle',
    'Неутронната звезда': 'Neutron Star',
    'Известният свят на Лари Нивън': 'Known Space',
    'Пръстеновият свят': 'Ringworld',
    'Инженерите на пръстеновия свят': 'The Ringworld Engineers',
    'Тронът на пръстеновия свят': 'Ringworld Throne',
    'Децата на пръстеновия свят': 'Ringworld\'s Children',
    'Снежен прах': 'Snow Crash',
    'Диамантената епоха': 'The Diamond Age',
    'Криптономикон': 'Cryptonomicon',
    'Анатем': 'Anathem',
    'Севенвес': 'Seveneves',
    'Невромантик': 'Neuromancer',
    'Граф Нула': 'Count Zero',
    'Мона Лиза овърдрайв': 'Mona Lisa Overdrive',
    'Виртуална светлина': 'Virtual Light',
    'Идора': 'Idoru',
    'Разпознаване на образи': 'Pattern Recognition',
    'Безкрайна шега': 'Infinite Jest',
    'Метро 2033': 'Metro 2033',
    'Метро 2034': 'Metro 2034',
    'Метро 2035': 'Metro 2035',
    'Пикник край пътя': 'Roadside Picnic',
    'Трудно е да бъдеш бог': 'Hard to Be a God',
    'Понеделник започва в събота': 'Monday Begins on Saturday',
    'Гадни улици': 'Ugly Swans',
    'Охлюв на склона': 'Snail on the Slope',
    'Соларис': 'Solaris',
    'Непобедимият': 'The Invincible',
    'Едем': 'Eden',
    'Глас на господаря': 'His Master\'s Voice',
    'Мирът на Земята': 'Peace on Earth',
    'Фиаско': 'Fiasco',
    
    // Bulgarian Literature
    'Под игото': 'Under the Yoke',
    'Бай Ганьо': 'Bai Ganyo',
    'Тютюн': 'Tobacco',
    'Железният светилник': 'The Iron Candlestick',
    'Хайка за вълци': 'Wolf Hunt',
    'Осъдени души': 'Doomed Souls',
    'Чичовци': 'The Uncles',
    'Когато гръм удари': 'When Thunder Strikes',
    'Нова земя': 'New Land',
    'Жътва': 'Harvest',
    'Жетварят': 'The Reaper',
    'Иван Кондарев': 'Ivan Kondarev',
    'Грях': 'Sin',
    'Гераците': 'The Gerak Family',
    'Индже': 'Indzhe',
    'Ангел Кънчев': 'Angel Kanchev',
    'Немили-недраги': 'Unwanted and Unloved',
    'Записки по българските въстания': 'Notes on the Bulgarian Uprisings',
    'Малкият Содом': 'Little Sodom',
    'Възвишение': 'Summit',
    'Физика на тъгата': 'Physics of Sorrow',
    'Естествен роман': 'Natural Novel',
    'Майките': 'The Mothers',
    'Кратка история на самолета': 'A Short History of the Airplane',
    'Поп Богомил и съвършенството на страха': 'Pop Bogomil and the Perfection of Fear',
    'Възвишение': 'Summit',
    'Хайка за вълци': 'Wolf Hunt',
    'Летопис на смутното време': 'Chronicle of Troubled Times',
    'Митология на прехода': 'Mythology of the Transition',
    'Балкански ритуал': 'Balkan Ritual',
    'Лавина': 'Avalanche',
    'Мъже': 'Men',
    'Дзифт': 'Zift',
    'Български работи': 'Bulgarian Affairs',
    'Времена на разделение': 'Times of Separation',
    'История на една мълчаливост': 'History of a Silence',
    'Процесът': 'The Trial',
    'Когато Ницше плака': 'When Nietzsche Wept',
    'Една седмица в рая': 'A Week in Paradise',
    'Истории за магия': 'Stories About Magic',
    'И всичко стана луна': 'And Everything Became Moon',
    'Остров Тамбукту': 'Timbuktu Island',
    'На куково лято': 'On Cuckoo Summer',
    'Лице': 'Face',
    'Разкази от други времена': 'Stories from Other Times',
    'Симеон': 'Simeon',
    'Кръв от къртица': 'Mole\'s Blood',
    'Светът е голям и спасение дебне отвсякъде': 'The World Is Big and Salvation Lurks Around the Corner',
    'Разходи по тавана': 'Walking on the Ceiling',
    'Анна Каренина': 'Anna Karenina',
    'Спомен за страха': 'Memory of Fear',
    'Пасиансът на архангелите': 'The Patience of Archangels',
    'Лице от Херкулан': 'Face from Herculaneum',
    'Граница': 'Border',
    
    // Additional Notable Works
    'Алхимикът': 'The Alchemist',
    'Единадесет минути': 'Eleven Minutes',
    'Вероника решава да умре': 'Veronika Decides to Die',
    'Брида': 'Brida',
    'Воинът на светлината': 'The Warrior of Light',
    'На брега на река Пиедра седнах и заплаках': 'By the River Piedra I Sat Down and Wept',
    'Захир': 'The Zahir',
    'Дяволът и сеньорита Прим': 'The Devil and Miss Prym',
    'Малкият принц': 'The Little Prince',
    'Сидхарта': 'Siddhartha',
    'Степният вълк': 'Steppenwolf',
    'Нарцис и Голдмунд': 'Narcissus and Goldmund',
    'Игра на стъклени перли': 'The Glass Bead Game',
    'Демиан': 'Demian',
    'Скотният двор': 'Animal Farm',
    'Бесове': 'Demons',
    'Портретът на Дориан Грей': 'The Picture of Dorian Gray',
    'Дракула': 'Dracula',
    'Франкенщайн': 'Frankenstein',
    'Пътешествията на Гъливер': 'Gulliver\'s Travels',
    'Хроника на предсказана смърт': 'Chronicle of a Death Foretold',
    'Сто години самота': 'One Hundred Years of Solitude',
    'Любов по време на холера': 'Love in the Time of Cholera',
    'Есента на патриарха': 'The Autumn of the Patriarch',
    'Генерал в лабиринта': 'The General in His Labyrinth',
    'Полковникът няма кой да му пише': 'No One Writes to the Colonel',
    'За любовта и други демони': 'Of Love and Other Demons',
    'Спомен за моите тъжни проститутки': 'Memories of My Melancholy Whores',
    'Живот на продажба': 'A Life for Sale',
    'Жажда за любов': 'Thirst for Love',
    'Шум на вълни': 'The Sound of Waves',
    'След банкета': 'After the Banquet',
    'Дневникът на луд старец': 'The Key',
    'Храмът на златния павилион': 'The Temple of the Golden Pavilion',
    'Изповедта на една маска': 'Confessions of a Mask',
    'Морякът, който падна в немилост пред морето': 'The Sailor Who Fell from Grace with the Sea',
    'Пролетен сняг': 'Spring Snow',
    'Бегач в пустошта': 'A Wild Sheep Chase',
    'Норвежка гора': 'Norwegian Wood',
    'Танцувай, танцувай, танцувай': 'Dance Dance Dance',
    'Хроника на птицата навиваща пружина': 'The Wind-Up Bird Chronicle',
    'Кафка на плажа': 'Kafka on the Shore',
    'След тъмнината': 'After Dark',
    '1Q84': '1Q84',
    'Безцветният Цукуру Тадзаки и неговите години на поклонничество': 'Colorless Tsukuru Tazaki and His Years of Pilgrimage',
    'Комисията по убийства': 'The Killing Commendatore',
    'Каква е тази История, Професоре?': 'The Professor and the Madman',
    'Спящата красавица': 'The Sleeping Beauty',
    'Лексикон': 'Lexicon',
    'Тишина': 'Silence',
    'Хилядолетието': 'Millennium',
    'Шифърът на Леонардо': 'The Da Vinci Code',
    'Пътят': 'The Road',
    'Наръчник на оптимиста': 'The Optimist\'s Handbook',
    'Ловец на елени': 'The Deer Hunter',
    'Пепел и диаманти': 'Ashes and Diamonds',
    'Майстора и Маргарита': 'The Master and Margarita',
    'Доктор Живаго': 'Doctor Zhivago',
    'Сърце на куче': 'Heart of a Dog',
    'Роковите яйца': 'The Fatal Eggs',
    'Бялата гвардия': 'The White Guard',
    'Тихият Дон': 'And Quiet Flows the Don',
    'Белият гвардеец': 'The White Guard',
    'Живот и съдба': 'Life and Fate',
    'Всичко тече': 'Everything Flows',
    'Един ден в живота на Иван Денисович': 'One Day in the Life of Ivan Denisovich',
    'Раковият корпус': 'Cancer Ward',
    'В първия кръг': 'The First Circle',
    'Архипелаг ГУЛАГ': 'The Gulag Archipelago',
    'Зъб за зъб': 'One to One',
    'Дъщерята на оптимиста': 'The Optimist\'s Daughter',
    'Часът на звездата': 'The Hour of the Star',
  'Семейна хроника': 'Family Chronicle',
  'Часът на смъртта': 'The Hour of Death',
  'Госпожица Юлия': 'Miss Julie',
  'Баща': 'The Father',
  'Госпожица Жули': 'Miss Julie',
  'Игра на сънища': 'A Dream Play',
  'Към Дамаск': 'To Damascus',
  'Пеликанът': 'The Pelican',
  'Соната на призраците': 'The Ghost Sonata',
  'Приказка': 'A Fairy Tale',
  'Отело и Дездемона': 'Othello and Desdemona',
  'Сватбата на Фигаро': 'The Marriage of Figaro',
  'Поеми в проза': 'Prose Poems',
  'Дон Жуан': 'Don Juan',
  'Фауст': 'Faust',
  'Ифигения в Таврида': 'Iphigenia in Tauris',
  'Избирателно сродство': 'Elective Affinities',
  'Страданията на младия Вертер': 'The Sorrows of Young Werther',
  'Вилхелм Майстер': 'Wilhelm Meister\'s Apprenticeship',
  'Вилхелм Майстер години на странстване': 'Wilhelm Meister\'s Journeyman Years',
  'Рейнеке Лис': 'Reynard the Fox',
  'Западно-източен диван': 'West-Eastern Divan',
  'Песен за камбаната': 'Song of the Bell',
  'Дон Карлос': 'Don Carlos',
  'Валенщайн': 'Wallenstein',
  'Мария Стюарт': 'Mary Stuart',
  'Вилхелм Тел': 'William Tell',
  'Орлеанската дева': 'The Maid of Orleans',
  'Разбойници': 'The Robbers',
  'Коварство и любов': 'Intrigue and Love',
  'Луиза Милер': 'Luise Miller',
  'Херман и Доротея': 'Hermann and Dorothea',
  'Хиперион': 'Hyperion',
  'Песента на нибелунгите': 'The Song of the Nibelungs',
  'Вълшебният рог на момъка': 'The Youth\'s Magic Horn',
  'Пътепис от Харц': 'Harz Journey',
  'Книга на песните': 'Book of Songs',
  'Германия. Зимна приказка': 'Germany. A Winter\'s Tale',
  'Атта Трол': 'Atta Troll',
  'Романсеро': 'Romanzero',
  'Рабин от Бахарах': 'The Rabbi of Bacharach',
  'Гренадири': 'The Grenadiers',
  'Лорелай': 'Lorelei',
  'Рим, град на съдбата': 'Rome, City of Fate',
  'Сънища и блянове': 'Dreams and Reveries',
  'Избрани стихотворения': 'Selected Poems',
  'Валпургиева нощ': 'Walpurgis Night',
  'Пепеляшка': 'Cinderella',
  'Червената шапчица': 'Little Red Riding Hood',
  'Спящата красавица': 'Sleeping Beauty',
  'Снежанка': 'Snow White',
  'Хензел и Гретел': 'Hansel and Gretel',
  'Трите прасенца': 'The Three Little Pigs',
  'Малечко Палечко': 'Tom Thumb',
  'Маша и мечокът': 'Masha and the Bear',
  'Златокоска и трите мечки': 'Goldilocks and the Three Bears',
  'Грозното патенце': 'The Ugly Duckling',
  'Палечка': 'Thumbelina',
  'Снежната кралица': 'The Snow Queen',
  'Малката русалка': 'The Little Mermaid',
  'Новите дрехи на царя': 'The Emperor\'s New Clothes',
  'Принцесата върху граховото зърно': 'The Princess and the Pea',
  'Дивите лебеди': 'The Wild Swans',
  'Сорока-бялата': 'The Wild Swans',
  'Дървото на тома': 'The Wish Tree',
  'Червените обувки': 'The Red Shoes',
  'Славеят': 'The Nightingale',
  'Андерсенови приказки': 'Andersen\'s Fairy Tales',
  'Джак и бобеното стъбло': 'Jack and the Beanstalk',
  'Синята брада': 'Bluebeard',
  'Котаракът в чизми': 'Puss in Boots',
  'Красавицата и звярът': 'Beauty and the Beast',
  'Алиса в страната на чудесата': 'Alice\'s Adventures in Wonderland',
  'Алиса в огледалния свят': 'Through the Looking-Glass',
  'Питър Пан': 'Peter Pan',
  'Мечо Пух': 'Winnie-the-Pooh',
  'Вятър във върбите': 'The Wind in the Willows',
  'Книга за джунглата': 'The Jungle Book',
  'Втора книга за джунглата': 'The Second Jungle Book',
  'Островът на съкровищата': 'Treasure Island',
  'Черната стрела': 'The Black Arrow',
  'Доктор Джекил и мистър Хайд': 'Strange Case of Dr Jekyll and Mr Hyde',
  'Похитеният': 'Kidnapped',
  'Мастър Балантрей': 'The Master of Ballantrae',
  'Катрионата': 'Catriona',
  'Дейвид Балфур': 'David Balfour',
  'Принц Ото': 'Prince Otto',
  'Клубът на самоубийците': 'The Suicide Club',
  'Нови арабски нощи': 'New Arabian Nights',
  'Приливите на Южните морета': 'South Sea Tales',
  'Маркхайм': 'Markheim',
  'Траун': 'Thrawn',
  'Тристрам Шенди': 'The Life and Opinions of Tristram Shandy, Gentleman',
  'Сантиментално пътешествие из Франция и Италия': 'A Sentimental Journey Through France and Italy',
  'Памела': 'Pamela, or Virtue Rewarded',
  'Кларис, или Историята на една млада дама': 'Clarissa, or, the History of a Young Lady',
  'Сър Чарлс Грандисън': 'The History of Sir Charles Grandison',
  'Джоузеф Андрюс': 'Joseph Andrews',
  'Джонатан Уайлд': 'The Life of Jonathan Wild, the Great',
  'Амелия': 'Amelia',
  'Пътешествие от този свят към другия': 'A Journey from This World to the Next',
  'История на Том Джоунс': 'The History of Tom Jones, a Foundling',
  'Родерик Рандъм': 'The Adventures of Roderick Random',
  'Перегрин Пикъл': 'The Adventures of Peregrine Pickle',
  'Фердинанд Граф Фатом': 'The Adventures of Ferdinand Count Fathom',
  'Сър Ланселот Грийвс': 'The Adventures of Sir Launcelot Greaves',
  'Хъмфри Клинкър': 'The Expedition of Humphry Clinker',
  'Пътешествие към центъра на Земята': 'Journey to the Center of the Earth',
  'Двадесет хиляди левги под водата': 'Twenty Thousand Leagues Under the Seas',
  'Около света за осемдесет дни': 'Around the World in Eighty Days',
  'Тайнственият остров': 'The Mysterious Island',
  'От Земята до Луната': 'From the Earth to the Moon',
  'Децата на капитан Грант': 'In Search of the Castaways',
  'Математически структури': 'Mathematical Structures',
  'Пет седмици в балон': 'Five Weeks in a Balloon',
  'Капитан Немо': 'Captain Nemo',
  'Михаил Строгов': 'Michael Strogoff',
  'Вечният Адам': 'The Eternal Adam',
  'Зеленият лъч': 'The Green Ray',
  'Замъкът в Карпатите': 'The Carpathian Castle',
  'Северът срещу Юга': 'North Against South',
  'Пътешественици по неволя': 'The Fur Country',
  'Ледената сфинкс': 'An Antarctic Mystery',
  'Драма в Ливония': 'A Drama in Livonia',
  'Завещанието на ексцентрика': 'The Will of an Eccentric',
  'Село във въздуха': 'The Village in the Treetops',
  'История на великите пътешественици': 'The Great Navigators of the Eighteenth Century',
  'Аспирин': 'Aspirin',
  'Островът на пингвините': 'Penguin Island',
  'Боговете жадуват': 'The Gods are Athirst',
  'Таис': 'Thais',
  'Червената лилия': 'The Red Lily',
  'Престъпление на Силвестър Бонар': 'The Crime of Sylvestre Bonnard',
  'Бунтът на ангелите': 'The Revolt of the Angels',
  'Градината на Епикур': 'The Garden of Epicurus',
  'Дом Джоунс и другарят': 'At the Sign of the Reine Pédauque',
  'Съвременна история': 'A Chronicle of Our Own Times',
  'Червени тамплиери': 'The Red Lily',
  'Стръмната пътека': 'The Steep Path',
  'Сполука': 'Success',
  'Вертер в Рим': 'Werther in Rome',
  'Погребан живот': 'Buried Life',
  'Мечта за щастие': 'Dream of Happiness',
  'Лирична душа': 'Lyrical Soul',
  'Вечерна звезда': 'Evening Star',
  'Избрани поеми': 'Selected Poems',
  'Елегия': 'Elegy',
  'Зимна нощ': 'Winter Night',
  'Шепот на тревите': 'Whisper of the Grasses',
  'Нежното утро': 'Tender Morning',
  'Бряг в мъгла': 'Shore in Fog',
  'Островът на щастието': 'Island of Happiness',
  'Слънчеви лъчи': 'Sunshine Rays',
  'Горски шум': 'Forest Noise',
  'Лунна пътека': 'Moon Path',
  'Пясъчни дюни': 'Sand Dunes',
  'Златна есен': 'Golden Autumn',
  'Пролетни води': 'Spring Waters',
  'Песни за любовта': 'Songs of Love',
  'Старият дъб': 'The Old Oak',
  'Вятър в листата': 'Wind in the Leaves',
  'Планински връх': 'Mountain Peak',
  'Градски светлини': 'City Lights',
  'Морски бриз': 'Sea Breeze',
  'Утринна роса': 'Morning Dew',
  'Буря над полето': 'Storm over the Field',
  'Пролетни цветя': 'Spring Flowers',
  'Летни дни': 'Summer Days',
  'Дъга след дъжд': 'Rainbow After Rain',
  'Студен декември': 'Cold December',
  'Пътят към дома': 'The Road Home',
  'Родна стряха': 'Native Roof',
  'Майчина песен': 'Mother\'s Song',
  'Тиха вечер': 'Quiet Evening',
  'Детски спомени': 'Childhood Memories',
  'Брегът на реката': 'The River Bank',
  'Шумът на гората': 'The Sound of the Forest',
  'Утринна звезда': 'Morning Star',
  'Вечерни сенки': 'Evening Shadows',
  'Първи сняг': 'First Snow',
  'Слънчев ден': 'Sunny Day',
  'Дъждовна нощ': 'Rainy Night',
  'Летен бриз': 'Summer Breeze',
  'Зимна приказка': 'Winter Tale',
  'Пролетен химн': 'Spring Hymn',
  'Есенен танц': 'Autumn Dance',
  'Морска пяна': 'Sea Foam',
  'Планинска пътека': 'Mountain Path',
  'Тъжна балада': 'Sad Ballad',
  'Слънчевата долина': 'The Sunny Valley',
  'Зимно утро': 'Winter Morning',
  'Пролетен дъжд': 'Spring Rain',
  'Градински цветя': 'Garden Flowers',
  'Горски извор': 'Forest Spring',
  'Планински поток': 'Mountain Stream',
  'Селска идилия': 'Rural Idyll',
  'Градски шум': 'City Noise',
  'Плажен залез': 'Beach Sunset',
  'Утринна мъгла': 'Morning Fog',
  'Нощно небе': 'Night Sky',
  'Звездна нощ': 'Starry Night',
  'Поле с макове': 'Field of Poppies',
  'Горски пожар': 'Forest Fire',
  'Тропически остров': 'Tropical Island',
  'Зимна река': 'Winter River',
  'Пролетна гора': 'Spring Forest',
  'Есенни листа': 'Autumn Leaves',
  'Лятно утро': 'Summer Morning',
  'Полунощ': 'Midnight',
  'Изгрев над морето': 'Sunrise Over the Sea',
  'Залез над планината': 'Sunset Over the Mountain',
  'Цветна градина': 'Flower Garden',
  'Дъждовен ден': 'Rainy Day',
  'Слънчева поляна': 'Sunny Meadow',
  'Морски фар': 'Lighthouse',
  'Тиха улица': 'Quiet Street',
  'Шумен площад': 'Noisy Square',
  'Стар мост': 'Old Bridge',
  'Нов път': 'New Road',
  'Висока кула': 'Tall Tower',
  'Дълбока пещера': 'Deep Cave',
  'Широка река': 'Wide River',
  'Тясна пътека': 'Narrow Path',
  'Стръмен склон': 'Steep Slope',
  'Плитък поток': 'Shallow Stream',
  'Дълго пътуване': 'Long Journey',
  'Кратка среща': 'Brief Encounter',
  'Първа любов': 'First Love',
  'Последно сбогом': 'Last Goodbye',
  'Нова надежда': 'New Hope',
  'Стар приятел': 'Old Friend',
  'Чужд град': 'Foreign City',
  'Родно село': 'Native Village',
  'Тежка работа': 'Hard Work',
  'Лек сън': 'Light Sleep',
  'Горчив спомен': 'Bitter Memory',
  'Сладък момент': 'Sweet Moment',
  'Бавен танц': 'Slow Dance',
  'Бърз ритъм': 'Fast Rhythm',
  'Тъмна нощ': 'Dark Night',
  'Светъл ден': 'Bright Day',
  'Студена зима': 'Cold Winter',
  'Топло лято': 'Warm Summer',
  'Висока планина': 'High Mountain',
  'Дълбоко море': 'Deep Sea',
  'Широко поле': 'Wide Field',
  'Тясна улица': 'Narrow Street',
  'Нова книга': 'New Book',
  'Стара история': 'Old Story',
  'Добър учител': 'Good Teacher',
  'Млад талант': 'Young Talent',
  'Стар мъдрец': 'Old Sage',
  'Малка стая': 'Small Room',
  'Голяма къща': 'Big House',
  'Тихи стъпки': 'Quiet Steps',
  'Шумен смях': 'Loud Laughter',
  'Лек бриз': 'Light Breeze',
  'Силен вятър': 'Strong Wind',
  'Дълбок сън': 'Deep Sleep',
  'Лека нощ': 'Good Night',
  'Добро утро': 'Good Morning',
  'Тежка сянка': 'Heavy Shadow',
  'Лека усмивка': 'Light Smile',
  'Топъл поглед': 'Warm Look',
  'Студена ръка': 'Cold Hand',
  'Нежен допир': 'Gentle Touch',
  'Груб звук': 'Rough Sound',
  'Мека светлина': 'Soft Light',
  'Ярка звезда': 'Bright Star',
  'Тъмна нощ': 'Dark Night',
  'Ясен ден': 'Clear Day',
  'Мрачен облак': 'Gloomy Cloud',
  'Чиста вода': 'Clean Water',
  'Мътна река': 'Muddy River',
  'Висок връх': 'High Peak',
  'Дълбока долина': 'Deep Valley',
  'Малко село': 'Small Village',
  'Голям град': 'Big City',
  'Стар замък': 'Old Castle',
  'Нова сграда': 'New Building',
  'Тиха музика': 'Quiet Music',
  'Шумен концерт': 'Loud Concert',
  'Бавен влак': 'Slow Train',
  'Бърза кола': 'Fast Car',
  'Дълга разходка': 'Long Walk',
  'Кратка почивка': 'Short Break',
  'Трудна задача': 'Difficult Task',
  'Лесно решение': 'Easy Solution',
  'Горчива истина': 'Bitter Truth',
  'Сладка лъжа': 'Sweet Lie',
  'Стара снимка': 'Old Photo',
  'Нов филм': 'New Movie',
  'Синьо небе': 'Blue Sky',
  'Зелена гора': 'Green Forest',
  'Червено цвете': 'Red Flower',
  'Жълто слънце': 'Yellow Sun',
  'Бяла птица': 'White Bird',
  'Черен облак': 'Black Cloud',
  'Сив ден': 'Gray Day',
  'Кафява земя': 'Brown Earth',
  'Златно сърце': 'Golden Heart',
  'Сребърна луна': 'Silver Moon',
  'Бронзов медал': 'Bronze Medal',
  'Железен характер': 'Iron Character',
  'Оловен войник': 'Lead Soldier',
  'Стъклена къща': 'Glass House',
  'Каменна стена': 'Stone Wall',
  'Дървено мостче': 'Wooden Bridge',
  'Метален мост': 'Metal Bridge',
  'Ледена скулптура': 'Ice Sculpture',
  'Воден път': 'Water Way',
  'Огнен танц': 'Fire Dance',
  'Въздушна стъпка': 'Air Step',
  'Земна тежест': 'Earth Weight',
  'Звезден час': 'Star Hour',
  'Луна в петък': 'Friday Moon',
  'Слънце в неделя': 'Sunday Sun',
  'Зимна ваканция': 'Winter Vacation',
  'Лятна почивка': 'Summer Break',
  'Пролетен празник': 'Spring Holiday',
  'Есенен бал': 'Autumn Ball',
  'Сутринно кафе': 'Morning Coffee',
  'Вечерен чай': 'Evening Tea',
  'Нощна смяна': 'Night Shift',
  'Дневна светлина': 'Daylight',
  'Утринна гимнастика': 'Morning Exercise',
  'Вечерна разходка': 'Evening Walk',
  'Нощна стража': 'Night Watch',
  'Дневник': 'Diary',
  'Пясъчен часовник': 'Hourglass',
  'Водна мелница': 'Water Mill',
  'Вятърна мелница': 'Windmill',
  'Слънчев часовник': 'Sundial',
  'Лунен календар': 'Lunar Calendar',
  'Звезден атлас': 'Star Atlas',
  'Небесна карта': 'Sky Map',
  'Морска карта': 'Sea Chart',
  'Пътна карта': 'Road Map',
  'Градски план': 'City Plan',
  'Селски път': 'Country Road',
  'Планинска пътека': 'Mountain Trail',
  'Горска пътека': 'Forest Path',
  'Речен бряг': 'River Bank',
  'Морски бряг': 'Seashore',
  'Езерен бряг': 'Lake Shore',
  'Океански бряг': 'Ocean Coast',
  'Пустинен оазис': 'Desert Oasis',
  'Арктически лед': 'Arctic Ice',
  'Тропически дъжд': 'Tropical Rain',
  'Екваториална гора': 'Equatorial Forest',
  'Полярна нощ': 'Polar Night',
  'Пустинна буря': 'Desert Storm',
  'Океанска вълна': 'Ocean Wave',
  'Планинска лавина': 'Mountain Avalanche',
  'Вулканично изригване': 'Volcanic Eruption',
  'Земетресение': 'Earthquake',
  'Торнадо': 'Tornado',
  'Ураган': 'Hurricane',
  'Цунами': 'Tsunami',
  'Слънчево затъмнение': 'Solar Eclipse',
  'Лунно затъмнение': 'Lunar Eclipse',
  'Метеоритен дъжд': 'Meteor Shower',
  'Полярно сияние': 'Aurora Borealis',
  'Дъга': 'Rainbow',
  'Светкавица': 'Lightning',
  'Гръмотевица': 'Thunder',
  'Мъгла': 'Fog',
  'Роса': 'Dew',
  'Скреж': 'Frost',
  'Лед': 'Ice',
  'Сняг': 'Snow',
  'Дъжд': 'Rain',
  'Градушка': 'Hail',
  'Виелица': 'Blizzard',
  'Пясъчна буря': 'Sandstorm',
  'Облак': 'Cloud',
  'Мъгла в долината': 'Valley Fog',
  'Планински вятър': 'Mountain Wind',
  'Морски бриз': 'Sea Breeze',
  'Песъчлив плаж': 'Sandy Beach',
  'Скалист бряг': 'Rocky Shore',
  'Коралов риф': 'Coral Reef',
  'Подводна пещера': 'Underwater Cave',
  'Соленото езеро': 'Salt Lake',
  'Сладководно езеро': 'Freshwater Lake',
  'Дълбок кладенец': 'Deep Well',
  'Планински извор': 'Mountain Spring',
  'Горски поток': 'Forest Stream',
  'Бързей': 'Rapids',
  'Водопад': 'Waterfall',
  'Блато': 'Swamp',
  'Мочурище': 'Marsh',
  'Тресавище': 'Bog',
  'Гейзер': 'Geyser',
  'Минерален извор': 'Mineral Spring',
  'Термален басейн': 'Thermal Pool',
  'Девственна гора': 'Virgin Forest',
  'Джунгла': 'Jungle',
  'Савана': 'Savanna',
  'Степ': 'Steppe',
  'Прерия': 'Prairie',
  'Тундра': 'Tundra',
  'Тайга': 'Taiga',
  'Пустиня': 'Desert',
  'Оазис': 'Oasis',
  'Каньон': 'Canyon',
  'Плато': 'Plateau',
  'Низина': 'Lowland',
  'Равнина': 'Plain',
  'Хълм': 'Hill',
  'Планина': 'Mountain',
  'Вулкан': 'Volcano',
  'Кратер': 'Crater',
  'Пещера': 'Cave',
  'Долина': 'Valley',
  'Клисура': 'Gorge',
  'Проход': 'Pass',
  'Архипелаг': 'Archipelago',
  'Остров': 'Island',
  'Полуостров': 'Peninsula',
  'Провлак': 'Isthmus',
  'Залив': 'Bay',
  'Пролив': 'Strait',
  'Фиорд': 'Fjord',
  'Делта': 'Delta',
  'Устие': 'Estuary',
  'Източник': 'Source',
  'Приток': 'Tributary',
  'Континент': 'Continent',
  'Материк': 'Mainland',
  'Полюс': 'Pole',
  'Екватор': 'Equator',
  'Тропик': 'Tropic',
  'Меридиан': 'Meridian',
  'Паралел': 'Parallel',
  'Хоризонт': 'Horizon',
  'Зенит': 'Zenith',
  'Надир': 'Nadir',
  'Изток': 'East',
  'Запад': 'West',
  'Север': 'North',
  'Юг': 'South',
  'Североизток': 'Northeast',
  'Северозапад': 'Northwest',
  'Югоизток': 'Southeast',
  'Югозапад': 'Southwest',
  'Елегия по загубения град': 'Elegy for a Lost City'
};

const recommendationCache = new Map();
const translationCache = new Map();

const translateTitle = async (title) => {
  if (translationCache.has(title)) {
    console.log('Returning cached translation for:', title);
    return translationCache.get(title);
  }

  if (titleMap[title]) {
    console.log('Using titleMap for:', title);
    translationCache.set(title, titleMap[title]);
    return titleMap[title];
  }

  if (/^[A-Za-z0-9\s.,!?'-]+$/.test(title)) {
    console.log('Title assumed to be English:', title);
    translationCache.set(title, title);
    return title;
  }

  try {
    const response = await fetch(`${LIBRE_TRANSLATE_BASE_URL}/translate`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        q: title,
        source: 'bg',
        target: 'en',
      }),
    });

    if (!response.ok) {
      throw new Error(`LibreTranslate HTTP error! Status: ${response.status}`);
    }

    const data = await response.json();
    if (!data.translatedText) {
      throw new Error('No translated text in response');
    }

    const translatedTitle = data.translatedText;
    console.log(`Translated "${title}" to "${translatedTitle}"`);
    translationCache.set(title, translatedTitle);
    return translatedTitle;
  } catch (error) {
    console.error(`Error translating title "${title}":`, error);
    translationCache.set(title, title);
    return title;
  }
};

export const getBookRecommendations = async (bookTitles, limit = 5) => {
  const cacheKey = `${bookTitles.sort().join(',')}:${limit}`;
  if (recommendationCache.has(cacheKey)) {
    console.log('Returning cached recommendations:', recommendationCache.get(cacheKey));
    return recommendationCache.get(cacheKey);
  }

  try {
    const translatedTitles = await Promise.all(
      bookTitles.map(async (title) => await translateTitle(title))
    );
    console.log('Translated titles:', translatedTitles);

    const query = translatedTitles.join(',');
    console.log('Query sent to TasteDive:', query, 'Limit:', limit);
    
    const tasteDiveResponse = await fetch(
      `${TASTE_DIVE_BASE_URL}?q=${encodeURIComponent(query)}&type=book&k=${TASTE_DIVE_API_KEY}&limit=${limit}`
    );
    if (!tasteDiveResponse.ok) {
      throw new Error(`TasteDive HTTP error! Status: ${tasteDiveResponse.status}`);
    }
    const tasteDiveData = await tasteDiveResponse.json();
    console.log('TasteDive API response:', JSON.stringify(tasteDiveData, null, 2));

    const similar = tasteDiveData.similar || tasteDiveData.Similar;
    if (!similar) {
      console.log('No "similar" field in TasteDive response');
      return [];
    }

    const results = similar.results || similar.Results || [];
    if (results.length === 0) {
      console.log('No results found in TasteDive response');
      return [];
    }

    const recommendations = results.map((item) => ({
      title: item.Name || item.name,
      type: item.Type || item.type || 'book',
    }));

    const recommendationsWithDetails = await Promise.all(
      recommendations.map(async (rec) => {
        try {
          const openLibraryResponse = await fetch(
            `${OPEN_LIBRARY_BASE_URL}/search.json?q=${encodeURIComponent(rec.title)}&limit=1`
          );
          if (!openLibraryResponse.ok) {
            throw new Error(`Open Library HTTP error! Status: ${openLibraryResponse.status}`);
          }
          const openLibraryData = await openLibraryResponse.json();
          const author = openLibraryData.docs?.[0]?.author_name?.[0] || 'Unknown Author';
          const cover_id = openLibraryData.docs?.[0]?.cover_i || null;
          return { ...rec, author, cover_id };
        } catch (error) {
          console.error(`Error fetching details for ${rec.title}:`, error);
          return { ...rec, author: 'Unknown Author', cover_id: null };
        }
      })
    );

    console.log('Parsed recommendations with details:', recommendationsWithDetails);
    recommendationCache.set(cacheKey, recommendationsWithDetails);
    return recommendationsWithDetails;
  } catch (error) {
    console.error('Error fetching recommendations:', error);
    return [];
  }
};